=== Acidburn0zzz/botbuilder-dotnet/prototypes/SkillManifest.schema-1-0-0.json
{
    "$id": "https://botframework.com/schemas/SkillManifest.schema-1-0-0.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Skill Manifest",
    "description": "A schema for Bot Framework skill manifests",
    "type": "object",
    "required": [
        "$id",
        "name",
        "version",
        "publisherName",
        "endpoints"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "The schema to verify this skill manifest against"
        },
        "$id": {
            "type": "string",
            "description": "The identifier for the skill manifest"
        },
        "name": {
            "type": "string",
            "description": "Name for your skill"
        },
        "version": {
            "type": "string",
            "description": "The version for the skill in Major.Minor format"
        },
        "description": {
            "type": "string",
            "description": "A human readable description for the skill."
        },
        "publisherName": {
            "type": "string",
            "description": "The name of the skill publisher."
        },
        "privacyUrl": {
            "type": "string",
            "format": "uri",
            "description": "The URL with the privacy description for the skill."
        },
        "copyright": {
            "type": "string",
            "description": "The copyright for the skill."
        },
        "license": {
            "type": "string",
            "description": "The licence agreement for the skill"
        },
        "iconUrl": {
            "type": "string",
            "format": "uri",
            "description": "Optional icon to be shown for the skill"
        },
        "tags": {
            "type": "array",
            "uniqueItems": true,
            "description": "An array of strings with tags for the skill"
        },
        "endpoints": {
            "type": "object",
            "description": "Endpoints supported by the skill",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/endpoint"
                    }
                ]
            }
        },
        "language": {
            "type": "object",
            "description": "Languge resources for the skill",
            "properties": {
                "models": {
                    "type": "object",
                    "description": "Locale -> Language models for the skill",
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "string",
                                "format": "uri"
                            }
                        ]
                    }
                },
                "intents": {
                    "type": "object",
                    "description": "map of intent to message activity to send",
                    "additionalProperties": {
                        "oneOf": [
                            {
                                "type": "string",
                                "format": "uri-reference"
                            }
                        ]
                    }
                }
            }
        },
        "activities": {
            "type": "object",
            "description": "Activity definitions",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/messageActivity"
                    },
                    {
                        "$ref": "#/definitions/eventOrInvokeActivity"
                    },
                    {
                        "$ref": "#/definitions/otherActivity"
                    }
                ]
            }
        },
        "sendActivities": {
            "type": "object",
            "description": "Activity definitions",
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/messageActivity"
                    },
                    {
                        "$ref": "#/definitions/eventOrInvokeActivity"
                    },
                    {
                        "$ref": "#/definitions/otherActivity"
                    }
                ]
            }
        },
        "definitions": {
            "type": "object",
            "description": "Definitions of the structure of object payloads",
            "additionalProperties": {
                "$ref": "http://json-schema.org/draft-07/schema#"
            }
        }
    },
    "definitions": {
        "endpoint": {
            "type": "object",
            "description": "Skill endpoint definition.",
            "properties": {
                "protocol": {
                    "type": "string",
                    "description": "Supported protocol",
                    "default": "BotframeworkV3"
                },
                "description": {
                    "type": "string",
                    "title": "Description",
                    "description": "Description of the endpoint.",
                    "examples": [
                        "Production bot"
                    ]
                },
                "endpointUrl": {
                    "type": "string",
                    "title": "Endpoint Url",
                    "descrition": "Endpoint of the skill",
                    "examples": [
                        "http://contoso.com/api/messaages"
                    ]
                },
                "msAppId": {
                    "type": "string",
                    "title": "Microsoft App Id",
                    "description": "The Microsoft AppId used for creating JWT tokens to authenticate this skill"
                }
            },
            "required": [
                "endpointUrl",
                "msAppId"
            ]
        },
        "eventOrInvokeActivity": {
            "type": "object",
            "description": "Define Activity.Type=Event|Invoke, with the name, the value that should be passed in on the activity and the shape of the EndOfConversation.Value result",
            "required": [
                "type",
                "name"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "event",
                        "invoke"
                    ]
                },
                "name": {
                    "type": "string",
                    "description": "The name property for the event",
                    "examples": [
                        "GetWeather"
                    ]
                },
                "description": {
                    "type": "string",
                    "title": "Description",
                    "description": "Description which describes the usage of the activity"
                },
                "value": {
                    "type": "object",
                    "description": "The JsonSchema definition of the shape of the value property that this event expects",
                    "$ref": "http://json-schema.org/draft-07/schema#"
                },
                "resultValue": {
                    "type": "object",
                    "description": "The JsonSchema definition of the shape of the resultValue that this event may produce",
                    "$ref": "http://json-schema.org/draft-07/schema#"
                }
            }
        },
        "messageActivity": {
            "type": "object",
            "description": "The description of the activity",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "message"
                    ]
                },
                "description": {
                    "type": "string",
                    "title": "Description",
                    "description": "Description which describes the usage of the activity"
                },
                "value": {
                    "type": "object",
                    "description": "The JsonSchema definition of the shape of the value property that this message would like to have",
                    "$ref": "http://json-schema.org/draft-07/schema#"
                }
            }
        },
        "otherActivity": {
            "type": "object",
            "description": "The description of the activity",
            "required": [
                "type"
            ],
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "contactRelationUpdate",
                        "conversationUpdate",
                        "typing",
                        "endOfConversation",
                        "deleteUserData",
                        "messageUpdate",
                        "messageDelete",
                        "installationUpdate",
                        "messageReaction",
                        "suggestion",
                        "trace",
                        "handoff"
                    ]
                },
                "description": {
                    "type": "string",
                    "title": "Description",
                    "description": "Description which describes the usage of the activity"
                }
            }
        }
    }
}

=== Acidburn0zzz/botbuilder-dotnet/prototypes/SkillManifest-EchoSkill.json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/botbuilder-dotnet/gabog/SkillsSecondPass/prototypes/SkillManifest.schema-1-0-0.json",
  "$id": "EchoSkill",
  "name": "Echo skill",
  "version": "1.0",
  "description": "This skill echoes whatever the user says",
  "publisherName": "Microsoft",
  "privacyUrl": "https://myskill.com/privacy.html",
  "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.",
  "license": "",
  "iconUrl": "https://myskill.com/icon.png",
  "tags": [
    "sample",
    "echo"
  ],
  "endpoints": {
    "production": {
      "protocol": "BotFrameworkV3",
      "description": "Production  endpoint for SkillBot.",
      "endpointUrl": "http://contoso.com/api/messages",
      "msAppId": "a0000f00-Ad00-a000-a000-a0000aaaAaa0"
    }
  },
  "language": {
    "intents": {
      "echo": "#/activities/message"
    }
  },
  "activities": {
    "message": {
      "type": "message",
      "description": "A message activity containing the utterance that the skill will echo back to the user"
    }
  }
}

=== Acidburn0zzz/botbuilder-dotnet/prototypes/SkillManifest-Simple.json
{
    "$schema": "file:///C:/Projects/Repos/botbuilder-dotnet/prototypes/SkillManifest.schema-1-0-0.json",
  "$id": "SkillBot",
    "name": "Demo skill bot with dialogs",
    "version": "1.0",
    "description": "This is a demo ",
    "publisherName": "Microsoft",
    "privacyUrl": "https://myskill.com/privacy.html",
    "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.",
    "license": "",
    "iconUrl": "https://myskill.com/icon.png",
    "tags": [
        "sample",
        "authentication",
        "travel"
    ],
    "endpoints": {
        "production": {
            "protocol": "BotframeworkV3",
            "description": "Production  endpoint for SkillBot.",
            "endpointUrl": "http://contoso.com/api/messages",
            "msAppId": "00000000-0000-0000-0000-00000000000"
        }
    },
    "language": {
        "models": {
            "en": "http://sample.com/SkillBot-en.lu"
        },
        "intents": {
          
        } 
        
    }
}
